<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>The Bit Brothers - $pageTitle$</title>
  <link rel="stylesheet" type="text/css" href="/styles/default.css" />
  <link rel="alternate" type="application/atom+xml" href="/feed/atom.xml" />
  <script type="text/javascript">  var disqus_developer = 1; </script>
</head>
